#!/bin/sh
if [ `uname -s` = 'Linux' ]
then
    case `uname -m` in
        ppc)
            echo -n powerpc
        ;;
        i?86)
            echo -n i386
        ;;
        *)
            echo `uname -i`
        ;;
    esac
else
        uname -p
fi
