#!/bin/sh
# Usage: cce CONSTANT_NAME
program=`mktemp /tmp/cce-XXXXXX`
source=$program".c"
cat >$source <<EOF
#include <stdio.h>
#include <GL/gl.h>
#include <GL/glu.h>

int main(int argc, char ** argv)
{          
    printf("%d", $*);
    return 0;
}
EOF
cc -I/usr/X11R6/include $source -o $program -L/usr/X11R6/lib -lGL -lGLU #2> /dev/null
if [ $? -ne 0 ]
then
    echo -13 THROW
    exit
fi
$program
rm -f $source $program
